version: "{branch}.build.{build}"
skip_tags: true

branches:
  only:
    - main

clone_folder:  c:\projects\immutable_cache

install:
  ps: .appveyor\install.ps1

cache:
  c:\build-cache -> appveyor.yml, .appveyor\install.ps1

environment:
  BIN_SDK_VER: 2.2.0
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      ARCH: x64
      VC: vs16
      PHP_VER: 8.0
      TS: 0
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      ARCH: x64
      VC: vs16
      PHP_VER: 8.0
      TS: 1
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      ARCH: x86
      VC: vs16
      PHP_VER: 8.0
      TS: 0
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      ARCH: x86
      VC: vs16
      PHP_VER: 8.0
      TS: 1

build_script:
  ps: .appveyor\build.ps1

after_build:
  ps: .appveyor\package.ps1

test_script:
  ps: .appveyor\test.ps1
